from __future__ import annotations


def combo(
    item_id: str,
    title: str,
    category_id: str,
    category_label: str,
    tools: list[str],
    summary: str,
    tags: list[str],
    importance: int = 70,
) -> dict:
    return {
        "id": item_id,
        "item_type": "combination",
        "title": title,
        "category_id": category_id,
        "category_label": category_label,
        "summary": summary,
        "tools": tools,
        "steps": [],
        "outputs": [],
        "tags": tags,
        "source_section": "2026_AI_工具实战指南 · Combination",
        "importance": importance,
    }


def workflow(
    item_id: str,
    title: str,
    category_id: str,
    category_label: str,
    tools: list[str],
    outputs: list[str],
    steps: list[str],
    tags: list[str],
    importance: int = 88,
) -> dict:
    return {
        "id": item_id,
        "item_type": "workflow",
        "title": title,
        "category_id": category_id,
        "category_label": category_label,
        "summary": "Project workflow from the PDF guide. Use it as a reusable plan for AI skill combinations.",
        "tools": tools,
        "steps": steps,
        "outputs": outputs,
        "tags": tags,
        "source_section": "2026_AI_工具实战指南 · 项目工作流",
        "importance": importance,
    }


AI_LIBRARY_ITEMS = [
    combo("combo-claude-outlook-calendar", "Claude + Outlook + Google Calendar", "ai-office", "AI OFFICE", ["Claude", "Outlook", "Google Calendar"], "Read email, extract schedule intent, and create calendar actions.", ["email", "calendar", "automation"], 86),
    combo("combo-raycast-claude-api", "Raycast AI + Claude API", "ai-agent", "AI AGENT", ["Raycast AI", "Claude API"], "Turn local Mac commands into fast AI-powered personal workflows.", ["mac", "shortcut", "api"], 78),
    combo("combo-deepl-claude-translation", "DeepL + Claude", "ai-office", "AI OFFICE", ["DeepL", "Claude"], "Translate first, then polish tone, terminology, and final writing quality.", ["translation", "writing"], 78),
    combo("combo-read-granola-calendar", "Read.ai + Granola + Calendar", "ai-office", "AI OFFICE", ["Read.ai", "Granola", "Calendar"], "Summarize meetings, compare notes, and turn decisions into schedule-aware follow-ups.", ["meeting", "notes"], 79),
    combo("combo-tactiq-linear-slack", "Tactiq + Linear + Slack", "ai-agent", "AI AGENT", ["Tactiq", "Linear", "Slack"], "Convert meeting transcripts into issues and send team updates.", ["meeting", "project-management"], 82),
    combo("combo-apple-notes-whisper-claude", "Apple Notes + Whisper + Claude", "ai-office", "AI OFFICE", ["Apple Notes", "Whisper", "Claude"], "Capture voice notes, transcribe them, and turn them into structured notes.", ["notes", "voice"], 76),
    combo("combo-telegram-claude-make", "Telegram Bot + Claude API + Make.com", "ai-agent", "AI AGENT", ["Telegram Bot", "Claude API", "Make.com"], "Create an IM bot that summarizes, extracts, OCRs, and routes tasks.", ["bot", "automation"], 80),
    combo("combo-reddit-perplexity-claude", "Reddit + Perplexity + Claude", "ai-research", "AI RESEARCH", ["Reddit", "Perplexity", "Claude"], "Mine user pain points, verify with search, and synthesize product insights.", ["research", "market"], 78),
    combo("combo-hn-rss-claude", "Hacker News + RSS + Claude", "ai-research", "AI RESEARCH", ["Hacker News", "RSS", "Claude"], "Monitor technical trends and generate a curated newsletter brief.", ["newsletter", "research"], 76),
    combo("combo-arxiv-notebooklm-claude", "arXiv + NotebookLM + Claude", "ai-research", "AI RESEARCH", ["arXiv", "NotebookLM", "Claude"], "Collect papers, digest sources, and write an explainable literature summary.", ["paper", "literature"], 84),
    combo("combo-elevenlabs-hume", "ElevenLabs + Hume AI", "ai-media", "AI MEDIA", ["ElevenLabs", "Hume AI"], "Generate voices and evaluate emotion, tone, and expressive delivery.", ["voice", "emotion"], 75),
    combo("combo-suno-stable-audio", "Suno + Stable Audio", "ai-media", "AI MEDIA", ["Suno", "Stable Audio"], "Generate music ideas in Suno and polish or extend sound assets with Stable Audio.", ["music", "audio"], 74),
    combo("combo-heygen-synthesia", "HeyGen + Synthesia", "ai-media", "AI MEDIA", ["HeyGen", "Synthesia"], "Produce avatar videos and compare UGC-style vs corporate training output.", ["avatar", "video"], 75),
    combo("combo-veo-runway-luma", "Veo + Runway + Luma", "ai-media", "AI MEDIA", ["Veo", "Runway", "Luma"], "Use Veo for high-quality generation, Runway for control, and Luma for camera motion.", ["video", "motion"], 88),
    combo("combo-imagen-veo-gemini", "Imagen + Veo + Gemini", "ai-media", "AI MEDIA", ["Imagen", "Veo", "Gemini"], "Create Google-native image-to-video workflows from prompt planning to video output.", ["image", "video"], 84),
    combo("combo-krea-magnific-photoshop", "Krea + Magnific + Photoshop AI", "ai-visual", "AI VISUAL", ["Krea", "Magnific", "Photoshop AI"], "Generate visual directions, upscale them, then refine details with Photoshop.", ["image", "upscale", "retouch"], 84),
    combo("combo-midjourney-recraft-krea", "Midjourney + Recraft + Krea", "ai-visual", "AI VISUAL", ["Midjourney", "Recraft", "Krea"], "Use Midjourney for style exploration, Recraft for vector/brand control, and Krea for production variants.", ["branding", "image"], 86),
    combo("combo-photoshop-topaz", "Photoshop AI + Topaz Gigapixel", "ai-visual", "AI VISUAL", ["Photoshop AI", "Topaz Gigapixel"], "Clean up images with generative tools and upscale final assets.", ["image", "upscale"], 78),
    combo("combo-photoroom-recraft-canva", "Photoroom + Recraft + Canva", "ai-visual", "AI VISUAL", ["Photoroom", "Recraft", "Canva"], "Remove backgrounds, rebuild product visuals, and layout marketing assets.", ["product", "design"], 82),
    combo("combo-ideogram-recraft-canva", "Ideogram + Recraft + Canva", "ai-visual", "AI VISUAL", ["Ideogram", "Recraft", "Canva"], "Generate accurate text visuals, convert into brand graphics, and package in Canva.", ["text-image", "brand"], 82),
    combo("combo-firefly-photoshop-premiere", "Adobe Firefly + Photoshop + Premiere AI", "ai-media", "AI MEDIA", ["Adobe Firefly", "Photoshop", "Premiere AI"], "Run an Adobe-native content pipeline from image generation to edit-ready video.", ["adobe", "video"], 83),
    combo("combo-magic-patterns-figma-v0", "Magic Patterns + Figma + v0", "ai-coding", "AI CODING", ["Magic Patterns", "Figma", "v0"], "Turn UI ideas into Figma designs and then React components.", ["ui", "frontend"], 84),
    combo("combo-cursor-continue", "Cursor + Continue.dev", "ai-coding", "AI CODING", ["Cursor", "Continue.dev"], "Pair a paid AI IDE with open/local coding assistance for flexible development.", ["coding", "ide"], 78),
    combo("combo-devin-cursor", "Devin + Cursor", "ai-coding", "AI CODING", ["Devin", "Cursor"], "Let Devin attempt PR-level work and use Cursor to inspect and refine output.", ["coding", "agent"], 82),
    combo("combo-cursor-claude-code-cline", "Cursor + Claude Code + Cline", "ai-coding", "AI CODING", ["Cursor", "Claude Code", "Cline"], "Use multiple coding agents for planning, terminal execution, and IDE edits.", ["coding", "agent"], 88),
    combo("combo-replit-vercel-stripe", "Replit Agent + Vercel + Stripe", "ai-coding", "AI CODING", ["Replit Agent", "Vercel", "Stripe"], "Build and deploy a small SaaS demo with payment integration.", ["saas", "deployment"], 84),
    combo("combo-v0-shadcn-tailwind", "v0 + shadcn/ui + Tailwind", "ai-coding", "AI CODING", ["v0", "shadcn/ui", "Tailwind"], "Generate polished React UI components with a consistent design system.", ["frontend", "ui"], 86),
    combo("combo-lovable-posthog-sentry", "Lovable + PostHog + Sentry", "ai-coding", "AI CODING", ["Lovable", "PostHog", "Sentry"], "Build a product and add analytics plus error monitoring.", ["saas", "analytics"], 82),
    combo("combo-bolt-lovable-claude-code", "Bolt.new + Lovable + Claude Code", "ai-coding", "AI CODING", ["Bolt.new", "Lovable", "Claude Code"], "Prototype fast, rebuild product flow, and harden code with Claude Code.", ["saas", "coding"], 86),
    combo("combo-copilot-claude-code-mcp", "GitHub Copilot + Claude Code MCP", "ai-coding", "AI CODING", ["GitHub Copilot", "Claude Code", "MCP"], "Use IDE completion plus repository-aware terminal agent workflows.", ["coding", "mcp"], 82),
    combo("combo-apollo-common-room-clay", "Apollo + Common Room + Clay", "ai-business", "AI BUSINESS", ["Apollo", "Common Room", "Clay"], "Build ICP lists, enrich leads, and prioritize sales outreach.", ["sales", "lead-gen"], 84),
    combo("combo-salesforce-close-claude", "Salesforce + Close + Claude", "ai-business", "AI BUSINESS", ["Salesforce", "Close", "Claude"], "Research accounts, draft outreach, and sync CRM updates.", ["crm", "sales"], 82),
    combo("combo-hubspot-klaviyo-claude", "HubSpot + Klaviyo + Claude", "ai-business", "AI BUSINESS", ["HubSpot", "Klaviyo", "Claude"], "Turn CRM segments into AI-written email campaigns.", ["marketing", "email"], 84),
    combo("combo-surfer-jasper-ahrefs", "Surfer SEO + Jasper + Ahrefs", "ai-business", "AI BUSINESS", ["Surfer SEO", "Jasper", "Ahrefs"], "Research keywords, build SEO briefs, and draft optimized content.", ["seo", "content"], 84),
    combo("combo-intercom-guru-claude", "Intercom + Guru + Claude", "ai-business", "AI BUSINESS", ["Intercom", "Guru", "Claude"], "Use support knowledge to generate better customer replies.", ["support", "knowledge-base"], 80),
    combo("combo-zendesk-linear-claude", "Zendesk + Linear + Claude", "ai-business", "AI BUSINESS", ["Zendesk", "Linear", "Claude"], "Turn support tickets into engineering issues and response drafts.", ["support", "engineering"], 82),
    combo("combo-snowflake-hex-claude-gamma", "Snowflake + Hex + Claude + Gamma", "ai-business", "AI BUSINESS", ["Snowflake", "Hex", "Claude", "Gamma"], "Analyze data, generate narrative insight, and present it as a deck.", ["data", "ppt"], 86),
    combo("combo-numerous-rows-bricks", "Numerous.ai + Rows + Bricks", "ai-office", "AI OFFICE", ["Numerous.ai", "Rows", "Bricks"], "Use AI spreadsheets and dashboards for business analysis.", ["spreadsheet", "dashboard"], 80),
    combo("combo-perplexity-felo-genspark", "Perplexity + Felo + Genspark", "ai-research", "AI RESEARCH", ["Perplexity", "Felo", "Genspark"], "Compare search agents for multilingual research and report generation.", ["search", "report"], 84),
    combo("combo-elicit-consensus-scite", "Elicit + Consensus + Scite", "ai-research", "AI RESEARCH", ["Elicit", "Consensus", "Scite"], "Find papers, compare claims, and inspect citation reliability.", ["paper", "research"], 86),
    combo("combo-notebooklm-khanmigo-quizlet", "NotebookLM + Khanmigo + Quizlet", "ai-research", "AI RESEARCH", ["NotebookLM", "Khanmigo", "Quizlet"], "Turn study materials into summaries, tutoring, and practice cards.", ["learning", "study"], 82),
    combo("combo-zotero-claude-notebooklm", "Zotero + Claude + NotebookLM", "ai-research", "AI RESEARCH", ["Zotero", "Claude", "NotebookLM"], "Organize references and generate grounded literature review notes.", ["citation", "literature"], 86),
    combo("combo-coze-dify-feishu", "Coze / Dify + Feishu / Notion", "ai-agent", "AI AGENT", ["Coze", "Dify", "Feishu", "Notion"], "Build a bot and connect it to team knowledge bases.", ["bot", "rag"], 82),
    combo("combo-manus-autoglm-coze", "Manus + AutoGLM + Coze", "ai-agent", "AI AGENT", ["Manus", "AutoGLM", "Coze"], "Compare Chinese agent tools for browser and workflow automation.", ["agent", "automation"], 80),
    combo("combo-ollama-openwebui-continue", "Ollama + Open WebUI + Continue.dev", "ai-models", "AI MODELS", ["Ollama", "Open WebUI", "Continue.dev"], "Run local models with a web UI and connect them to the coding environment.", ["local-llm", "coding"], 84),
    combo("combo-lmstudio-anythingllm-obsidian", "LM Studio + AnythingLLM + Obsidian", "ai-models", "AI MODELS", ["LM Studio", "AnythingLLM", "Obsidian"], "Create a local knowledge base with local models and notes.", ["local-llm", "knowledge"], 82),
    combo("combo-n8n-claude-api-localdb", "n8n + Claude API + Local Database", "ai-agent", "AI AGENT", ["n8n", "Claude API", "Local Database"], "Automate business processes with API calls and persistent storage.", ["workflow", "database"], 86),
    combo("combo-meshy-tripo-hunyuan3d", "Meshy + Tripo + Hunyuan3D", "ai-visual", "AI VISUAL", ["Meshy", "Tripo", "Hunyuan3D"], "Generate and compare 3D assets across tools.", ["3d", "asset"], 78),
    combo("combo-blender-claude-meshy", "Blender connector + Claude + Meshy", "ai-visual", "AI VISUAL", ["Blender", "Claude", "Meshy"], "Control Blender workflows with Claude and generate base 3D models.", ["3d", "blender"], 82),
    combo("combo-unity-chatgpt-cursor", "Unity + ChatGPT + Cursor", "ai-coding", "AI CODING", ["Unity", "ChatGPT", "Cursor"], "Plan game mechanics and implement them in a coding IDE.", ["game", "coding"], 80),
    combo("combo-discord-suno-midjourney", "Discord + Suno + Midjourney Bot", "ai-media", "AI MEDIA", ["Discord", "Suno", "Midjourney"], "Run a community creative server with music and image bots.", ["community", "creative"], 74),
    combo("combo-slack-notion-linear", "Slack + Notion + Linear", "ai-agent", "AI AGENT", ["Slack", "Notion", "Linear"], "Turn team chat into specs, tasks, and project tracking.", ["team", "project-management"], 82),
    combo("combo-claude-skill-mcp", "Claude + Custom Skill + MCP", "ai-agent", "AI AGENT", ["Claude", "Skills", "MCP"], "Package SOPs as skills and connect them to tools through MCP.", ["mcp", "skill"], 90),
    combo("combo-claude-code-hooks-subagents", "Claude Code Hooks + Subagents", "ai-coding", "AI CODING", ["Claude Code", "Hooks", "Subagents"], "Use hooks and subagents for more controlled software development workflows.", ["coding", "agent"], 88),

    workflow("workflow-ebook", "项目工作流 1：两周做一本可发布电子书", "ai-office", "AI OFFICE", ["Claude", "NotebookLM", "Sudowrite", "Grammarly", "Midjourney", "Recraft", "Pandoc", "Calibre"], ["EPUB", "封面", "营销文案", "有声版本"], ["Claude 做选题、大纲和章节计划", "NotebookLM 消化资料并生成 grounded notes", "Sudowrite/Claude 进行长文写作", "Grammarly 做语言校对", "Midjourney/Recraft 做封面", "Pandoc/Calibre 输出 EPUB"], ["book", "writing", "publishing"], 92),
    workflow("workflow-saas-72h", "项目工作流 3：72 小时做一个 SaaS", "ai-coding", "AI CODING", ["Claude", "Figma Make", "Stitch", "Lovable", "Cursor", "Claude Code", "v0", "Vercel", "Cloudflare", "PostHog", "HubSpot"], ["带支付、登录、数据库的全栈应用"], ["Claude 产出 PRD 和功能规格", "Figma Make/Stitch 生成 UI", "Lovable 生成 React + Supabase 原型", "Cursor/Claude Code 修代码和补后端", "v0 生成组件", "Vercel/Cloudflare 部署", "PostHog/HubSpot 做增长和追踪"], ["saas", "full-stack", "deployment"], 96),
    workflow("workflow-music-mv", "项目工作流 4：两周做原创歌曲 + MV", "ai-media", "AI MEDIA", ["Claude", "Suno", "Mureka", "Udio", "Luma", "Kling", "CapCut", "DistroKid"], ["原创歌曲", "配套 MV", "Spotify/网易云/YouTube 发布素材"], ["Claude 写歌词、设定和 MV 分镜", "Suno/Mureka 生成歌曲候选", "Udio 做音质和版本调整", "Luma/Kling 生成视频镜头", "CapCut 剪辑", "DistroKid 或平台发布"], ["music", "mv", "video"], 90),
    workflow("workflow-product-launch", "项目工作流 6：新品全平台上线", "ai-business", "AI BUSINESS", ["Perplexity", "秘塔 AI", "Claude", "Apollo", "Common Room", "Photoroom", "Adobe Firefly", "Magnific", "Ideogram", "HeyGen", "Klaviyo", "Surfer SEO"], ["产品图 ×20", "短视频 ×5", "Listing 文案", "邮件营销流程"], ["Perplexity/秘塔做市场调研", "Claude/Apollo 找 KOL 和潜在合作", "Photoroom/Firefly 做商品图", "Magnific/Ideogram 提升视觉和文字图", "HeyGen 做视频素材", "Claude 写 landing page 和邮件", "Klaviyo/Surfer 做自动化和 SEO"], ["ecommerce", "marketing"], 92),
    workflow("workflow-research-paper", "项目工作流 7：三个月做研究论文", "ai-research", "AI RESEARCH", ["Elicit", "Consensus", "Semantic Scholar", "Scite", "NotebookLM", "Zotero", "Claude", "Python", "Grammarly", "Overleaf", "Beautiful.ai"], ["LaTeX 论文", "参考文献库", "答辩 PPT"], ["Elicit/Consensus/Semantic Scholar 找论文", "Scite 检查引用", "NotebookLM 整理资料", "Zotero 管理文献", "Claude + Python 分析数据", "Claude/Sudowrite 写论文", "Grammarly 校对", "Overleaf 排版", "Beautiful.ai 做答辩 PPT"], ["paper", "latex", "research"], 96),
    workflow("workflow-b2b-sdr", "项目工作流 9：B2B SDR 外呼流水线", "ai-business", "AI BUSINESS", ["Claude", "Apollo", "Clay", "ZoomInfo", "Common Room", "Outreach", "HubSpot"], ["500 条目标账户", "CRM 更新", "Call prep brief", "A/B outreach"], ["Claude 定义 ICP", "Apollo/Clay/ZoomInfo 拉取线索", "Common Room 做意图信号", "Claude 做 account research", "Outreach 发送 A/B 邮件", "HubSpot 回写 CRM", "Claude 生成 call prep"], ["sales", "sdr", "crm"], 92),
    workflow("workflow-newsletter", "项目工作流 10：每周 AI Newsletter", "ai-research", "AI RESEARCH", ["Perplexity Deep Research", "秘塔 AI", "Claude", "NotebookLM", "Ideogram", "Recraft", "Substack", "Mailchimp", "Granola"], ["每周 newsletter", "LinkedIn 内容", "配图"], ["Perplexity/秘塔收集 50 条素材", "Claude 做主题筛选和结构", "NotebookLM 生成 brief", "Claude 起草和改写", "Ideogram/Recraft 做头图", "Substack/Mailchimp 发布", "Granola 整理访谈材料"], ["newsletter", "content"], 90),
    workflow("workflow-real-estate", "项目工作流 12：房产研究与谈判策略", "ai-research", "AI RESEARCH", ["Manus", "Genspark", "Claude", "Sheets connector", "Claude in Excel", "Perplexity", "DocuSign"], ["候选房源对比表", "区域基础研究", "谈判策略"], ["Manus/Genspark 搜集房源和区域信息", "Claude + Sheets 整理对比表", "Claude in Excel 做财务测算", "Perplexity 做区域和政策研究", "Claude 生成谈判策略", "DocuSign 处理合同"], ["real-estate", "analysis"], 86),
    workflow("workflow-job-offer", "项目工作流 13：四周拿到 3+ offer", "ai-business", "AI BUSINESS", ["Claude", "Manus", "LinkedIn", "Apollo", "ElevenLabs", "Yoodli"], ["定制简历", "Cover letter", "面试准备材料", "薪资谈判 brief"], ["Claude 优化简历和定位", "Manus 搜集公司和岗位", "Claude 定制 cover letter", "LinkedIn/Apollo 找 hiring manager", "Claude 做面试题和 STAR 框架", "ElevenLabs/Yoodli 做口语模拟", "Claude 做薪资谈判"], ["career", "job"], 88),
    workflow("workflow-bio-research", "项目工作流 15：公开数据到生物研究投稿", "ai-research", "AI RESEARCH", ["Claude", "PubMed", "Wiley", "Nextflow", "scvi-tools", "BioRender", "matplotlib", "Sudowrite", "Grammarly", "Overleaf"], ["分析 pipeline", "论文初稿", "图表材料"], ["Claude 做科学问题选择", "PubMed/Wiley 做文献检索", "Claude 开发 Nextflow pipeline", "scvi-tools 做单细胞 QC", "BioRender/matplotlib 画图", "Sudowrite/Grammarly 写作校对", "Overleaf 排版"], ["bio", "research", "pipeline"], 88),
    workflow("workflow-contract-automation", "项目工作流 16：合同从收件箱到签字归档", "ai-agent", "AI AGENT", ["Gmail connector", "Claude", "DocuSign", "SignNow", "Egnyte", "Box", "Notion"], ["合同 triage", "风险摘要", "签字流程", "归档记录"], ["Gmail 读取合同邮件", "Claude triage NDA 为 GREEN/YELLOW/RED", "Claude review-contract 检查条款", "Claude 输出风险评估", "DocuSign/SignNow 发起签字", "Egnyte/Box 归档", "Notion 记录元数据"], ["legal", "automation"], 94),
    workflow("workflow-brand-identity", "项目工作流 17：五天做 Brand Identity", "ai-visual", "AI VISUAL", ["Claude", "Midjourney", "Ideogram", "Recraft", "Canva", "Figma", "Adobe Firefly"], ["Logo", "品牌视觉方向", "社媒模板", "Pitch deck 素材"], ["Claude 定义品牌策略", "Midjourney/Ideogram 做方向探索", "Recraft 做 logo/vector", "Canva/Figma 做模板", "Firefly 做延展素材"], ["brand", "visual"], 86),
    workflow("workflow-game-demo", "项目工作流 18：两周做可玩游戏 demo", "ai-coding", "AI CODING", ["Claude", "Meshy", "Tripo", "Blender", "Suno", "ElevenLabs", "Cursor", "Claude Code", "Unity", "Unreal", "Veo", "Runway", "Recraft"], ["Windows demo", "宣传视频", "Steam 页面素材"], ["Claude 写 design doc 和关卡机制", "Meshy/Tripo 生成 3D 资产", "Blender connector 做整理", "Suno/ElevenLabs 生成音频", "Cursor/Claude Code 写 Unity/Unreal 逻辑", "Veo/Runway 做预告片", "Recraft 做商店视觉"], ["game", "demo", "3d"], 92),
    workflow("workflow-company-report", "项目工作流 19：三周做公司深度研报", "ai-business", "AI BUSINESS", ["Perplexity Deep Research", "Claude", "BigQuery", "Claude in Excel", "Granola", "Otter", "Kimi", "秘塔 AI", "Beautiful.ai"], ["30 页研报", "Excel 模型", "汇报 PPT"], ["Perplexity 做行业资料", "Claude + BigQuery 汇总数据", "Claude in Excel 做 DCF 和敏感性分析", "Granola/Otter 整理访谈", "Kimi 消化 PDF", "Claude 做图表和写作", "Beautiful.ai 生成汇报 PPT"], ["finance", "research", "ppt"], 92),
    workflow("workflow-support-automation", "项目工作流 20：客服 80% 工单 AI 自助解决", "ai-business", "AI BUSINESS", ["Coze", "Dify", "RAG", "Intercom", "Zendesk", "Claude", "Linear"], ["RAG Bot", "客服知识库", "工单升级流程"], ["Coze/Dify 搭建客服 RAG Bot", "整理 FAQ 和知识库", "Intercom/Zendesk 接入对话", "Claude 做复杂回复和总结", "Linear 回流产品缺陷", "持续优化召回和回答质量"], ["support", "rag", "automation"], 90),
]
