from __future__ import annotations


AI_SKILL_CATEGORIES = [
    {"id": "ai-models", "label": "AI MODELS", "color": "#ffb066", "radius": 1.45, "tilt": [0.26, 0.10, 0.04], "speed": 0.060},
    {"id": "ai-coding", "label": "AI CODING", "color": "#7ed6e6", "radius": 1.78, "tilt": [-0.38, 0.34, 0.12], "speed": 0.044},
    {"id": "ai-visual", "label": "AI VISUAL", "color": "#e69aa3", "radius": 2.11, "tilt": [0.62, -0.22, 0.10], "speed": 0.034},
    {"id": "ai-media", "label": "AI MEDIA", "color": "#b99cff", "radius": 2.44, "tilt": [-0.70, -0.10, -0.15], "speed": 0.027},
    {"id": "ai-office", "label": "AI OFFICE", "color": "#ffe27a", "radius": 2.77, "tilt": [0.14, 0.52, -0.08], "speed": 0.022},
    {"id": "ai-research", "label": "AI RESEARCH", "color": "#91e6a7", "radius": 3.10, "tilt": [-0.18, -0.46, 0.18], "speed": 0.018},
    {"id": "ai-agent", "label": "AI AGENT", "color": "#ff8ed1", "radius": 3.43, "tilt": [0.78, 0.22, -0.18], "speed": 0.015},
    {"id": "ai-business", "label": "AI BUSINESS", "color": "#9fb7ff", "radius": 3.76, "tilt": [-0.58, 0.58, 0.22], "speed": 0.013},
]


def skill(
    id: str,
    name: str,
    category_id: str,
    tool: str,
    stage: str,
    tags: list[str],
    description: str,
    *,
    core: bool = False,
    importance: int = 50,
    examples: list[str] | None = None,
) -> dict:
    category = next(item for item in AI_SKILL_CATEGORIES if item["id"] == category_id)
    return {
        "id": id,
        "name": name,
        "category_id": category_id,
        "category_label": category["label"],
        "tool": tool,
        "stage": stage,
        "description": description,
        "tags": tags,
        "examples": examples or [],
        "input_types": ["text", "file", "prompt"],
        "output_types": ["plan", "draft", "asset"],
        "difficulty": 2,
        "importance": importance,
        "is_core": core,
        "is_active": True,
    }


AI_SKILLS = [
    skill("claude-complex-reasoning", "用 Claude 做复杂推理与长文写作", "ai-models", "Claude", "planning", ["claude", "reasoning", "writing", "long context"], "适合长文档理解、复杂推理、方案设计和高质量写作。", core=True, importance=98),
    skill("chatgpt-task-planning", "用 ChatGPT 做通用问答与任务规划", "ai-models", "ChatGPT", "planning", ["chatgpt", "gpt", "planning", "operator"], "适合通用问答、拆任务、写草稿和日常 AI 助手场景。", core=True, importance=96),
    skill("gemini-workspace-long-context", "用 Gemini 处理长上下文和 Google Workspace", "ai-models", "Gemini", "planning", ["gemini", "google", "workspace", "long context"], "适合 Google 生态、长上下文资料处理和多模态任务。", core=True, importance=92),
    skill("perplexity-source-search", "用 Perplexity 做带来源的搜索问答", "ai-models", "Perplexity", "research", ["search", "sources", "research"], "适合需要来源、引用和快速事实核查的问题。", core=True, importance=94),
    skill("deepseek-chinese-reasoning", "用 DeepSeek 做中文推理与代码辅助", "ai-models", "DeepSeek", "planning", ["deepseek", "chinese", "reasoning", "code"], "适合中文推理、代码解释和低成本模型任务。", core=True, importance=90),
    skill("kimi-long-pdf-reading", "用 Kimi 阅读长文档和 PDF", "ai-models", "Kimi", "research", ["kimi", "pdf", "long document"], "适合长 PDF、中文资料和多文档问答。", core=True, importance=88),
    skill("qwen-enterprise-model", "用 Qwen 做中文多模态与企业应用", "ai-models", "Qwen", "planning", ["qwen", "multimodal", "enterprise"], "适合中文企业场景、多模态和模型生态接入。", core=True, importance=84),
    skill("doubao-lightweight-creation", "用 Doubao 做中文创作和轻量任务", "ai-models", "Doubao", "writing", ["doubao", "chinese", "content"], "适合中文内容创作、短任务和轻量 AI 助手。", core=True, importance=78),
    skill("glm-browser-agent", "用 GLM / AutoGLM 做中文 Agent 任务", "ai-models", "GLM", "automation", ["glm", "autoglm", "agent"], "适合中文浏览器 Agent、信息处理和自动化任务。", core=True, importance=78),

    skill("cursor-code-build", "用 Cursor 编写和重构代码", "ai-coding", "Cursor", "execution", ["cursor", "code", "refactor", "ide"], "适合在 IDE 中编写、理解、重构和调试代码。", core=True, importance=98),
    skill("claude-code-large-repo", "用 Claude Code 处理大型代码库", "ai-coding", "Claude Code", "execution", ["claude code", "repo", "terminal", "subagent"], "适合命令行工程任务、跨文件修改和大型代码库分析。", core=True, importance=96),
    skill("github-copilot-completion", "用 GitHub Copilot 做 IDE 补全", "ai-coding", "GitHub Copilot", "execution", ["copilot", "autocomplete", "ide"], "适合日常补全、代码建议和快速实现。", core=True, importance=90),
    skill("windsurf-agent-coding", "用 Windsurf 做 Agentic coding", "ai-coding", "Windsurf", "execution", ["windsurf", "cascade", "agent"], "适合 Agent 驱动的多步骤代码修改。", core=True, importance=86),
    skill("replit-agent-app", "用 Replit Agent 快速生成应用", "ai-coding", "Replit Agent", "prototype", ["replit", "agent", "app"], "适合从自然语言快速生成可运行应用。", core=True, importance=84),
    skill("bolt-fullstack-prototype", "用 Bolt.new 生成全栈原型", "ai-coding", "Bolt.new", "prototype", ["bolt", "full stack", "prototype"], "适合快速生成前后端原型。", core=True, importance=84),
    skill("v0-react-ui", "用 v0 生成 React / shadcn UI", "ai-coding", "v0", "design", ["v0", "react", "shadcn", "ui"], "适合根据描述生成 React UI 和组件代码。", core=True, importance=88),
    skill("lovable-saas-prototype", "用 Lovable 快速搭建 SaaS 原型", "ai-coding", "Lovable", "prototype", ["lovable", "saas", "supabase"], "适合快速做产品原型、SaaS 页面和轻量后端。", core=True, importance=84),
    skill("devin-auto-pr", "用 Devin 做自动 PR / 工程任务", "ai-coding", "Devin", "execution", ["devin", "pr", "engineering"], "适合自动完成工程任务和提交 PR。", core=True, importance=76),
    skill("continue-local-code-model", "用 Continue.dev 接入本地模型写代码", "ai-coding", "Continue.dev", "execution", ["continue", "local model", "coding"], "适合在 IDE 中连接本地或自定义模型。", core=True, importance=74),

    skill("midjourney-concept-art", "用 Midjourney 生成高质量概念图", "ai-visual", "Midjourney", "design", ["midjourney", "image", "concept"], "适合高质量视觉风格、概念图和创意画面。", core=True, importance=98),
    skill("flux-realistic-image", "用 FLUX 生成真实感图片", "ai-visual", "FLUX", "design", ["flux", "image", "realistic"], "适合真实感图像生成和开放模型工作流。", core=True, importance=88),
    skill("ideogram-text-poster", "用 Ideogram 生成带文字的海报图", "ai-visual", "Ideogram", "design", ["ideogram", "poster", "text"], "适合带文字的海报、标题图和商业图。", core=True, importance=86),
    skill("firefly-commercial-image", "用 Adobe Firefly 做商业安全图像生成", "ai-visual", "Adobe Firefly", "design", ["firefly", "commercial", "adobe"], "适合 Adobe 生态和商业安全图像生成。", core=True, importance=84),
    skill("recraft-brand-visual", "用 Recraft 做 Logo 和品牌视觉", "ai-visual", "Recraft", "design", ["recraft", "logo", "brand"], "适合 Logo、图标和品牌视觉系统。", core=True, importance=82),
    skill("imagen-google-image", "用 Imagen 生成 Google 系图像", "ai-visual", "Imagen", "design", ["imagen", "google", "image"], "适合 Google 生态的高质量图像生成。", core=True, importance=78),
    skill("photoshop-ai-generative-fill", "用 Photoshop AI 修图和 Generative Fill", "ai-visual", "Photoshop AI", "editing", ["photoshop", "generative fill", "retouch"], "适合修图、扩图、去除物体和视觉精修。", core=True, importance=92),
    skill("magnific-topaz-upscale", "用 Magnific / Topaz 做图片放大增强", "ai-visual", "Magnific / Topaz", "editing", ["upscale", "enhance", "topaz"], "适合图片高清放大和细节增强。", core=True, importance=80),
    skill("krea-realtime-visual", "用 Krea 做实时视觉生成", "ai-visual", "Krea", "design", ["krea", "realtime", "visual"], "适合实时图像生成和视觉探索。", core=True, importance=76),
    skill("canva-light-design", "用 Canva 做轻量设计排版", "ai-visual", "Canva", "production", ["canva", "design", "layout"], "适合海报、社媒图、PPT 和轻量排版。", core=True, importance=88),

    skill("veo-video-generation", "用 Veo 生成高质量视频", "ai-media", "Veo", "production", ["veo", "video", "google"], "适合高质量视频生成和镜头草稿。", core=True, importance=96),
    skill("runway-video-editing", "用 Runway 做视频生成和编辑", "ai-media", "Runway", "production", ["runway", "video", "editing"], "适合视频生成、编辑、补帧和创意短片。", core=True, importance=92),
    skill("kling-chinese-video", "用 Kling 做中文视频生成", "ai-media", "Kling", "production", ["kling", "video", "chinese"], "适合中文语境下的视频生成。", core=True, importance=84),
    skill("luma-video-3d", "用 Luma 做视频和 3D 场景生成", "ai-media", "Luma", "production", ["luma", "video", "3d"], "适合视频、镜头和 3D 场景相关生成。", core=True, importance=80),
    skill("hailuo-minimax-video", "用 Hailuo / MiniMax 做中文视频", "ai-media", "Hailuo", "production", ["hailuo", "minimax", "video"], "适合中文短视频和视频创意。", core=True, importance=78),
    skill("suno-song-bgm", "用 Suno 生成歌曲和 BGM", "ai-media", "Suno", "audio", ["suno", "song", "bgm"], "适合歌曲、广告 BGM 和音乐 demo。", core=True, importance=92),
    skill("udio-music-generation", "用 Udio 生成音乐", "ai-media", "Udio", "audio", ["udio", "music"], "适合音乐生成、风格探索和歌曲草稿。", core=True, importance=82),
    skill("elevenlabs-voiceover", "用 ElevenLabs 生成语音和配音", "ai-media", "ElevenLabs", "audio", ["voice", "tts", "elevenlabs"], "适合高质量配音、旁白和语音克隆。", core=True, importance=90),
    skill("heygen-avatar-video", "用 HeyGen 生成数字人视频", "ai-media", "HeyGen", "production", ["avatar", "video", "ugc"], "适合数字人、UGC 风格视频和营销视频。", core=True, importance=84),
    skill("capcut-ai-editing", "用 CapCut 做 AI 剪辑", "ai-media", "CapCut", "editing", ["capcut", "editing", "subtitle"], "适合剪辑、字幕、短视频包装和发布。", core=True, importance=82),

    skill("gamma-ppt-generation", "用 Gamma 生成 PPT", "ai-office", "Gamma", "delivery", ["ppt", "slides", "deck"], "适合快速生成演示文稿和网页式 deck。", core=True, importance=96, examples=["我今天想做一个 PPT"]),
    skill("canva-magic-design", "用 Canva Magic Design 做演示设计", "ai-office", "Canva", "design", ["canva", "presentation", "design"], "适合演示视觉设计、模板和排版。", core=True, importance=90),
    skill("beautiful-ai-business-deck", "用 Beautiful.ai 做商业演示", "ai-office", "Beautiful.ai", "delivery", ["business", "deck", "slides"], "适合商业汇报、董事会材料和规范化演示。", core=True, importance=78),
    skill("aippt-chinese-slides", "用 AiPPT.cn 生成中文 PPT", "ai-office", "AiPPT.cn", "delivery", ["aippt", "ppt", "chinese"], "适合中文 PPT 快速生成。", core=True, importance=78),
    skill("excel-copilot-analysis", "用 Microsoft Excel Copilot 分析表格", "ai-office", "Excel Copilot", "analysis", ["excel", "copilot", "analysis"], "适合 Excel 表格分析、公式和图表。", core=True, importance=90),
    skill("claude-excel-reasoning", "用 Claude in Excel 做复杂表格推理", "ai-office", "Claude in Excel", "analysis", ["claude", "excel", "reasoning"], "适合复杂表格解释、统计和建模辅助。", core=True, importance=86),
    skill("rows-numerous-ai-sheet", "用 Rows / Numerous.ai 做 AI 表格", "ai-office", "Rows / Numerous.ai", "analysis", ["rows", "spreadsheet", "ai"], "适合 AI-native 表格和自动化数据处理。", core=True, importance=76),
    skill("gpt-for-work-sheets", "用 GPT for Work 处理 Excel / Sheets", "ai-office", "GPT for Work", "analysis", ["sheets", "excel", "gpt"], "适合表格批处理、文本生成和数据清理。", core=True, importance=76),
    skill("notion-ai-knowledge", "用 Notion AI 做知识整理", "ai-office", "Notion AI", "organization", ["notion", "knowledge", "docs"], "适合知识库、会议记录和文档整理。", core=True, importance=86),
    skill("google-workspace-ai", "用 Google Workspace AI 处理 Docs / Gmail / Sheets", "ai-office", "Google Workspace AI", "organization", ["google", "docs", "gmail", "sheets"], "适合 Google 办公套件内的写作、总结和表格工作。", core=True, importance=84),

    skill("notebooklm-source-grounded", "用 NotebookLM 阅读和总结资料", "ai-research", "NotebookLM", "research", ["notebooklm", "pdf", "knowledge"], "适合基于资料源做总结、问答和学习笔记。", core=True, importance=96),
    skill("perplexity-deep-research", "用 Perplexity Deep Research 做深度搜索", "ai-research", "Perplexity", "research", ["deep research", "search", "sources"], "适合带来源的研究报告和事实核查。", core=True, importance=94),
    skill("elicit-academic-research", "用 Elicit 做学术研究", "ai-research", "Elicit", "research", ["academic", "paper", "research"], "适合论文检索、研究问题和证据整理。", core=True, importance=86),
    skill("consensus-paper-answers", "用 Consensus 查论文结论", "ai-research", "Consensus", "research", ["consensus", "paper", "evidence"], "适合快速查看研究共识和论文证据。", core=True, importance=82),
    skill("scite-citation-check", "用 Scite 检查论文引用关系", "ai-research", "Scite", "research", ["citation", "paper", "scite"], "适合判断论文被支持、反驳或提及的关系。", core=True, importance=78),
    skill("semantic-scholar-discovery", "用 Semantic Scholar 找学术资料", "ai-research", "Semantic Scholar", "research", ["semantic scholar", "paper"], "适合学术资料发现和相关文献追踪。", core=True, importance=78),
    skill("zotero-reference-management", "用 Zotero 管理文献", "ai-research", "Zotero", "organization", ["zotero", "reference", "bibtex"], "适合文献库、引用、BibTeX 和论文写作准备。", core=True, importance=84),
    skill("genspark-research-agent", "用 Genspark 做研究型 Agent", "ai-research", "Genspark", "research", ["genspark", "agent", "report"], "适合自动生成研究报告、PPT 和信息整合。", core=True, importance=80),
    skill("felo-multilingual-search", "用 Felo 做多语言搜索", "ai-research", "Felo", "research", ["felo", "search", "multilingual"], "适合跨语言搜索和资料整理。", core=True, importance=74),
    skill("phind-technical-search", "用 Phind 搜索技术问题", "ai-research", "Phind", "research", ["phind", "technical", "coding"], "适合工程技术问题搜索和代码解释。", core=True, importance=76),

    skill("chatgpt-agent-operator", "用 ChatGPT Agent / Operator 操作网页任务", "ai-agent", "ChatGPT Agent", "automation", ["operator", "agent", "browser"], "适合网页操作、表单任务和自动执行流程。", core=True, importance=94),
    skill("claude-mcp-connectors", "用 Claude MCP 连接外部工具", "ai-agent", "Claude MCP", "automation", ["mcp", "connectors", "tools"], "适合连接 Notion、Slack、Drive、数据库和设计工具。", core=True, importance=96),
    skill("manus-general-agent", "用 Manus 做通用 Agent 任务", "ai-agent", "Manus", "automation", ["manus", "agent"], "适合通用多步骤 Agent 任务。", core=True, importance=84),
    skill("genspark-super-agent", "用 Genspark Super Agent 生成报告 / PPT", "ai-agent", "Genspark Super Agent", "automation", ["report", "ppt", "agent"], "适合自动化生成报告、PPT 和研究材料。", core=True, importance=82),
    skill("autoglm-browser-agent", "用 AutoGLM 做中文浏览器 Agent", "ai-agent", "AutoGLM", "automation", ["autoglm", "browser", "chinese"], "适合中文浏览器自动化和网页任务。", core=True, importance=78),
    skill("n8n-ai-workflow", "用 n8n 连接 AI 工作流", "ai-agent", "n8n", "automation", ["n8n", "workflow", "automation"], "适合把 API、数据库、消息和 AI 串成工作流。", core=True, importance=88),
    skill("dify-ai-app", "用 Dify 搭建 AI 应用", "ai-agent", "Dify", "automation", ["dify", "rag", "app"], "适合搭建 RAG、AI 应用和工作流。", core=True, importance=82),
    skill("coze-bot-agent", "用 Coze 搭建中文 Bot / Agent", "ai-agent", "Coze", "automation", ["coze", "bot", "agent"], "适合中文 Bot、Agent 和工作流搭建。", core=True, importance=78),
    skill("raycast-ai-local-automation", "用 Raycast AI 做本地快捷自动化", "ai-agent", "Raycast AI", "automation", ["raycast", "mac", "automation"], "适合 Mac 本地快捷命令、prompt 和轻量自动化。", core=True, importance=74),
    skill("claude-code-hooks-subagents", "用 Claude Code Hooks / Subagents 做工程自动化", "ai-agent", "Claude Code", "automation", ["hooks", "subagents", "engineering"], "适合工程流水线、代码检查和自动化任务。", core=True, importance=86),

    skill("jasper-marketing-copy", "用 Jasper 写营销文案", "ai-business", "Jasper", "writing", ["jasper", "marketing", "copy"], "适合营销文案、广告语和品牌内容。", core=True, importance=82),
    skill("copy-ai-sales-content", "用 Copy.ai 生成销售内容", "ai-business", "Copy.ai", "writing", ["sales", "copy", "email"], "适合销售邮件、外联话术和内容批量生成。", core=True, importance=78),
    skill("grammarly-wordtune-polish", "用 Grammarly / Wordtune 优化英文写作", "ai-business", "Grammarly / Wordtune", "review", ["english", "writing", "grammar"], "适合英文润色、语气调整和语法检查。", core=True, importance=84),
    skill("surferseo-content-optimization", "用 SurferSEO 做 SEO 内容优化", "ai-business", "SurferSEO", "marketing", ["seo", "content", "keyword"], "适合 SEO 文章结构、关键词和排名优化。", core=True, importance=80),
    skill("ahrefs-semrush-keywords", "用 Ahrefs / Semrush 做关键词研究", "ai-business", "Ahrefs / Semrush", "research", ["seo", "keyword", "competitor"], "适合关键词研究、竞品流量和 SEO 机会发现。", core=True, importance=82),
    skill("hubspot-breeze-crm", "用 HubSpot Breeze AI 做 CRM 和营销", "ai-business", "HubSpot", "marketing", ["crm", "hubspot", "marketing"], "适合 CRM、营销自动化和客户运营。", core=True, importance=84),
    skill("klaviyo-email-automation", "用 Klaviyo 做邮件营销自动化", "ai-business", "Klaviyo", "marketing", ["email", "automation", "ecommerce"], "适合电商邮件、用户分层和营销自动化。", core=True, importance=78),
    skill("apollo-sales-leads", "用 Apollo 做销售线索挖掘", "ai-business", "Apollo", "sales", ["apollo", "leads", "sales"], "适合 ICP、销售线索和外联名单。", core=True, importance=76),
    skill("salesforce-claude-customer-data", "用 Salesforce + Claude 分析客户数据", "ai-business", "Salesforce + Claude", "analysis", ["salesforce", "customer", "crm"], "适合客户数据分析、销售洞察和 CRM 总结。", core=True, importance=76),
    skill("intercom-zendesk-support", "用 Intercom / Zendesk + Claude 做客服支持", "ai-business", "Intercom / Zendesk", "support", ["support", "zendesk", "intercom"], "适合客服工单总结、回答建议和用户支持。", core=True, importance=78),

    skill("figma-make-ui", "用 Figma Make 生成 UI 原型", "ai-visual", "Figma Make", "design", ["figma", "ui", "prototype"], "适合从描述生成 UI 原型和界面草图。", importance=70),
    skill("framer-ai-site", "用 Framer AI 生成网站页面", "ai-visual", "Framer", "design", ["framer", "website"], "适合生成营销页和交互式网站。", importance=68),
    skill("uizard-wireframe", "用 Uizard 生成线框和界面草案", "ai-visual", "Uizard", "design", ["wireframe", "ui"], "适合早期 UI 线框和界面草案。", importance=62),
    skill("tldraw-excalidraw-figma", "用 Tldraw / Excalidraw / Figma 做草图到 UI", "ai-visual", "Tldraw", "design", ["sketch", "figma", "whiteboard"], "适合手绘草图转界面想法。", importance=62),
    skill("meshy-3d-generation", "用 Meshy 生成 3D 资产", "ai-media", "Meshy", "production", ["3d", "meshy"], "适合 3D 模型和资产生成。", importance=66),
    skill("blender-claude-connector", "用 Blender connector + Claude 调整 3D 场景", "ai-media", "Blender + Claude", "production", ["blender", "3d", "mcp"], "适合 3D 场景、材质和建模辅助。", importance=64),
    skill("otter-fireflies-meeting", "用 Otter / Fireflies 做会议记录", "ai-office", "Otter / Fireflies", "organization", ["meeting", "transcript"], "适合会议转写、总结和 action items。", importance=70),
    skill("granola-meeting-notes", "用 Granola 做智能会议笔记", "ai-office", "Granola", "organization", ["meeting", "notes"], "适合会议笔记、跟进事项和知识沉淀。", importance=72),
    skill("khanmigo-ai-learning", "用 Khanmigo 做 AI 学习辅导", "ai-research", "Khanmigo", "learning", ["learning", "education"], "适合学习辅导、课程拆解和练习。", importance=64),
    skill("quizlet-ai-flashcards", "用 Quizlet 做复习卡片", "ai-research", "Quizlet", "learning", ["flashcards", "learning"], "适合知识点记忆和复习。", importance=62),
    skill("slack-notion-linear-workflow", "用 Slack + Notion + Linear 管理团队工作流", "ai-agent", "Slack / Notion / Linear", "automation", ["slack", "notion", "linear"], "适合团队消息、知识库和任务同步。", importance=72),
    skill("make-telegram-claude-api", "用 Make.com + Telegram Bot + Claude API 搭自动化", "ai-agent", "Make.com", "automation", ["make", "telegram", "api"], "适合聊天机器人和自动化流程。", importance=66),
    skill("bigquery-looker-claude", "用 BigQuery / Looker + Claude 做数据分析", "ai-business", "BigQuery / Looker", "analysis", ["bigquery", "looker", "data"], "适合业务数据查询、洞察和可视化解释。", importance=70),
    skill("snowflake-hex-claude", "用 Snowflake / Hex + Claude 做数据报告", "ai-business", "Snowflake / Hex", "analysis", ["snowflake", "hex", "report"], "适合 SQL 分析、数据报告和汇报材料。", importance=70),
]
