from __future__ import annotations


CATEGORIES = {
    "ai-models": "AI MODELS",
    "ai-coding": "AI CODING",
    "ai-visual": "AI VISUAL",
    "ai-media": "AI MEDIA",
    "ai-office": "AI OFFICE",
    "ai-research": "AI RESEARCH",
    "ai-agent": "AI AGENT",
    "ai-business": "AI BUSINESS",
}


def _skill(
    id: str,
    name: str,
    category_id: str,
    tool: str,
    stage: str,
    tags: list[str],
    description: str,
    url: str,
    *,
    sub_skill_id: str,
    sub_skill_label: str,
    core: bool = False,
    importance: int = 82,
    input_types: list[str] | None = None,
    output_types: list[str] | None = None,
) -> dict:
    return {
        "id": id,
        "name": name,
        "category_id": category_id,
        "category_label": CATEGORIES[category_id],
        "sub_skill_id": sub_skill_id,
        "sub_skill_label": sub_skill_label,
        "tool": tool,
        "stage": stage,
        "description": description,
        "tags": tags,
        "examples": [url],
        "input_types": input_types or ["prompt", "text", "file"],
        "output_types": output_types or ["plan", "draft", "asset"],
        "difficulty": 2,
        "importance": importance,
        "is_core": core,
        "is_active": True,
    }


def _combo(
    item_id: str,
    title: str,
    category_id: str,
    tools: list[str],
    summary: str,
    tags: list[str],
    importance: int = 86,
    *,
    sub_skill_id: str = "",
    sub_skill_label: str = "",
) -> dict:
    return {
        "id": item_id,
        "item_type": "combination",
        "title": title,
        "category_id": category_id,
        "category_label": CATEGORIES[category_id],
        "sub_skill_id": sub_skill_id,
        "sub_skill_label": sub_skill_label,
        "summary": summary,
        "tools": tools,
        "steps": [],
        "outputs": [],
        "tags": tags,
        "source_section": "2026 Hot AI Stack Refresh",
        "importance": importance,
    }


def _workflow(
    item_id: str,
    title: str,
    category_id: str,
    tools: list[str],
    outputs: list[str],
    steps: list[str],
    tags: list[str],
    importance: int = 90,
    *,
    sub_skill_id: str = "",
    sub_skill_label: str = "",
) -> dict:
    return {
        "id": item_id,
        "item_type": "workflow",
        "title": title,
        "category_id": category_id,
        "category_label": CATEGORIES[category_id],
        "sub_skill_id": sub_skill_id,
        "sub_skill_label": sub_skill_label,
        "summary": f"2026 热门 AI 工具组合方案：{title}。工具链：{' + '.join(tools[:8])}。适合需要稳定产出、可复用 SOP 和多工具协作的场景。",
        "tools": tools,
        "steps": steps,
        "outputs": outputs,
        "tags": tags,
        "source_section": "2026 Hot AI Stack Refresh",
        "importance": importance,
    }


def hot_ai_skill_items() -> list[dict]:
    return [
        _skill("deepseek-reasoning-coding", "用 DeepSeek 做推理和代码问答", "ai-models", "DeepSeek", "推理", ["中文模型", "推理", "代码"], "目的：低成本推理与代码辅助。1给背景 2要求逐步推理 3让它输出可执行方案", "https://chat.deepseek.com", sub_skill_id="models-chinese-ecosystem", sub_skill_label="Chinese Model Ecosystem", core=True, importance=92),
        _skill("grok-realtime-x-research", "用 Grok 查实时趋势和 X 舆情", "ai-models", "Grok", "检索", ["实时", "X", "趋势"], "目的：实时舆情。1输入话题 2对比观点 3提炼风险和机会", "https://grok.com", sub_skill_id="models-general-assistants", sub_skill_label="General AI Assistants", importance=84),
        _skill("qwen-app-task-assistant", "用 Qwen 做中文任务助理", "ai-models", "Qwen", "任务", ["中文模型", "任务执行", "阿里生态"], "目的：中文工作/生活任务。1说明目标 2拆步骤 3输出可执行清单", "https://chat.qwen.ai", sub_skill_id="models-chinese-ecosystem", sub_skill_label="Chinese Model Ecosystem", core=True, importance=88),
        _skill("yuanbao-wechat-research", "用腾讯元宝查微信生态资料", "ai-models", "腾讯元宝", "检索", ["中文模型", "微信", "资料"], "目的：中文互联网资料核查。1输入问题 2看来源 3整理摘要", "https://yuanbao.tencent.com", sub_skill_id="models-chinese-ecosystem", sub_skill_label="Chinese Model Ecosystem", importance=84),
        _skill("wenxiaoyan-chinese-office", "用文小言做中文办公问答", "ai-models", "文小言", "写作", ["中文模型", "办公", "问答"], "目的：中文办公写作。1贴材料 2要求结构 3生成版本", "https://yiyan.baidu.com", sub_skill_id="models-chinese-ecosystem", sub_skill_label="Chinese Model Ecosystem", importance=78),
        _skill("mistral-le-chat", "用 Le Chat 做欧洲模型助手", "ai-models", "Mistral Le Chat", "规划", ["通用助手", "开源生态", "多语"], "目的：多语种助手。1描述任务 2补上下文 3导出答案", "https://chat.mistral.ai", sub_skill_id="models-general-assistants", sub_skill_label="General AI Assistants", importance=80),
        _skill("windsurf-agentic-ide", "用 Windsurf 做 Agentic IDE 开发", "ai-coding", "Windsurf", "编码", ["IDE", "Agent", "重构"], "目的：代理式开发。1打开仓库 2给任务 3审查改动和测试", "https://windsurf.com", sub_skill_id="coding-code-edit-review", sub_skill_label="Code Edit & Review", core=True, importance=90),
        _skill("cline-vscode-agent", "用 Cline 在 VS Code 里跑编码 Agent", "ai-coding", "Cline", "编码", ["VS Code", "Agent", "终端"], "目的：本地 IDE 代理。1选模型 2授权命令 3逐步确认 diff", "https://cline.bot", sub_skill_id="coding-code-edit-review", sub_skill_label="Code Edit & Review", importance=86),
        _skill("roo-code-agent", "用 Roo Code 做多模式代码代理", "ai-coding", "Roo Code", "编码", ["VS Code", "Agent", "多模式"], "目的：编码/架构/调试分模式执行。1选模式 2给上下文 3检查输出", "https://roocode.com", sub_skill_id="coding-code-edit-review", sub_skill_label="Code Edit & Review", importance=82),
        _skill("coderabbit-pr-review", "用 CodeRabbit 做 PR 审查", "ai-coding", "CodeRabbit", "审查", ["PR", "代码审查", "质量"], "目的：PR 自动审查。1连接仓库 2提交 PR 3处理建议", "https://www.coderabbit.ai", sub_skill_id="coding-devops-testing", sub_skill_label="DevOps, QA & Security", importance=84),
        _skill("firebase-studio-app-builder", "用 Firebase Studio 做全栈应用原型", "ai-coding", "Firebase Studio", "原型", ["全栈", "Firebase", "原型"], "目的：从想法到可运行 Web App。1写需求 2生成应用 3接 Firebase 服务", "https://firebase.studio", sub_skill_id="coding-app-prototype", sub_skill_label="App & Prototype Build", core=True, importance=88),
        _skill("sourcegraph-cody-code-search", "用 Sourcegraph Cody 查大型代码库", "ai-coding", "Sourcegraph Cody", "检索", ["代码搜索", "大型仓库", "问答"], "目的：理解大型仓库。1索引代码 2问模块关系 3生成修改点", "https://sourcegraph.com/cody", sub_skill_id="coding-code-edit-review", sub_skill_label="Code Edit & Review", importance=80),
        _skill("krea-realtime-visual", "用 Krea 做实时视觉探索", "ai-visual", "Krea", "设计", ["图像生成", "实时", "风格"], "目的：快速找视觉方向。1上传参考 2调风格 3导候选", "https://www.krea.ai", sub_skill_id="visual-image-generation", sub_skill_label="Image Generation & Editing", core=True, importance=88),
        _skill("leonardo-production-art", "用 Leonardo 做素材和游戏美术", "ai-visual", "Leonardo", "设计", ["图像生成", "游戏资产", "素材"], "目的：批量生产视觉素材。1设风格 2生成资产 3筛选放大", "https://leonardo.ai", sub_skill_id="visual-image-generation", sub_skill_label="Image Generation & Editing", importance=80),
        _skill("topaz-gigapixel-upscale", "用 Topaz Gigapixel 放大图片", "ai-visual", "Topaz Gigapixel", "增强", ["放大", "修复", "图片增强"], "目的：修复低清图片。1导入图片 2选模型 3导出高分辨率", "https://www.topazlabs.com/gigapixel", sub_skill_id="visual-image-generation", sub_skill_label="Image Generation & Editing", importance=78),
        _skill("photoroom-product-visuals", "用 Photoroom 做商品图", "ai-visual", "Photoroom", "电商", ["商品图", "抠图", "电商"], "目的：电商商品视觉。1上传产品 2换背景 3批量导出", "https://www.photoroom.com", sub_skill_id="visual-brand-design", sub_skill_label="Brand & Graphic Design", importance=82),
        _skill("comfyui-custom-image-pipeline", "用 ComfyUI 搭自定义图像流程", "ai-visual", "ComfyUI", "工作流", ["开源", "图像工作流", "节点"], "目的：可控图像生成。1搭节点 2接模型 3批量生成", "https://www.comfy.org", sub_skill_id="visual-image-generation", sub_skill_label="Image Generation & Editing", importance=84),
        _skill("luma-dream-machine-video", "用 Luma Dream Machine 做镜头视频", "ai-media", "Luma", "视频", ["视频生成", "镜头", "运动"], "目的：镜头感视频。1写镜头 2给参考图 3生成版本", "https://lumalabs.ai/dream-machine", sub_skill_id="media-video-editing", sub_skill_label="Video Generation & Editing", core=True, importance=88),
        _skill("pika-video-effects", "用 Pika 做短视频特效", "ai-media", "Pika", "视频", ["视频生成", "特效", "社媒"], "目的：短视频特效。1上传素材 2选效果 3导出发布", "https://pika.art", sub_skill_id="media-video-editing", sub_skill_label="Video Generation & Editing", importance=82),
        _skill("hailuo-video-cn", "用海螺 AI 做中文视频生成", "ai-media", "海螺 AI", "视频", ["中文视频", "短片", "多模态"], "目的：中文短片。1写分镜 2生成镜头 3进剪辑软件", "https://hailuoai.com", sub_skill_id="media-video-editing", sub_skill_label="Video Generation & Editing", importance=82),
        _skill("udio-music-production", "用 Udio 做歌曲版本探索", "ai-media", "Udio", "音频", ["音乐", "歌曲", "版本"], "目的：音乐风格探索。1写主题 2生成多版 3挑主歌副歌", "https://www.udio.com", sub_skill_id="media-audio-voice-music", sub_skill_label="Audio, Voice & Music", importance=84),
        _skill("descript-podcast-edit", "用 Descript 剪播客和口播视频", "ai-media", "Descript", "剪辑", ["播客", "转写", "剪辑"], "目的：按文字剪音视频。1导入素材 2删文字 3导出成片", "https://www.descript.com", sub_skill_id="media-audio-voice-music", sub_skill_label="Audio, Voice & Music", core=True, importance=86),
        _skill("opusclip-video-repurpose", "用 OpusClip 切长视频为短视频", "ai-media", "OpusClip", "发布", ["短视频", "切片", "社媒"], "目的：长视频复用。1上传长视频 2自动切片 3改标题字幕", "https://www.opus.pro", sub_skill_id="media-social-publishing", sub_skill_label="Social Content Publishing", importance=82),
        _skill("m365-copilot-work", "用 Microsoft 365 Copilot 处理办公流", "ai-office", "Microsoft 365 Copilot", "办公", ["Office", "企业", "文档"], "目的：在 Word/Excel/Outlook/Teams 中写作、分析和总结。1选文档 2提问 3校对输出", "https://learn.microsoft.com/en-us/microsoft-365-copilot/microsoft-365-copilot-overview", sub_skill_id="office-doc-writing", sub_skill_label="Docs, Writing & Translation", core=True, importance=94),
        _skill("gemini-workspace-office", "用 Gemini for Workspace 做 Google 办公", "ai-office", "Gemini for Workspace", "办公", ["Google", "Docs", "Gmail"], "目的：在 Gmail/Docs/Sheets 里生成和总结。1打开文件 2调用 Gemini 3复核结果", "https://workspace.google.com/solutions/ai/", sub_skill_id="office-doc-writing", sub_skill_label="Docs, Writing & Translation", importance=86),
        _skill("granola-meeting-notes", "用 Granola 做高质量会议笔记", "ai-office", "Granola", "会议", ["会议", "笔记", "行动项"], "目的：保留个人笔记并自动整理纪要。1开会记录 2补充手记 3生成行动项", "https://www.granola.ai", sub_skill_id="office-meetings-knowledge", sub_skill_label="Meetings, Notes & Knowledge", core=True, importance=88),
        _skill("read-ai-meeting-intelligence", "用 Read.ai 做会议洞察", "ai-office", "Read.ai", "会议", ["会议", "转写", "洞察"], "目的：会议总结和参与度分析。1接日历 2自动入会 3导出摘要", "https://www.read.ai", sub_skill_id="office-meetings-knowledge", sub_skill_label="Meetings, Notes & Knowledge", importance=82),
        _skill("napkin-visual-explain", "用 Napkin 把文字变图解", "ai-office", "Napkin", "图解", ["图解", "PPT", "解释"], "目的：把段落变成视觉解释图。1粘文本 2选图形 3导入汇报", "https://www.napkin.ai", sub_skill_id="office-ppt-decks", sub_skill_label="PPT, Decks & Proposals", importance=82),
        _skill("chatgpt-deep-research", "用 ChatGPT Deep Research 做深度报告", "ai-research", "ChatGPT Deep Research", "研究", ["深度研究", "来源", "报告"], "目的：多步骤资料研究。1给问题和范围 2等待检索 3检查引用", "https://chatgpt.com", sub_skill_id="research-web-search", sub_skill_label="Web Search & Source QA", core=True, importance=94),
        _skill("gemini-deep-research", "用 Gemini Deep Research 做资料调研", "ai-research", "Gemini Deep Research", "研究", ["深度研究", "Google", "报告"], "目的：生成结构化调研报告。1定义范围 2审计划 3导出结论", "https://gemini.google.com", sub_skill_id="research-web-search", sub_skill_label="Web Search & Source QA", importance=88),
        _skill("genspark-report-agent", "用 Genspark 生成研究页面和报告", "ai-research", "Genspark", "研究", ["搜索", "报告", "页面"], "目的：把搜索变成可读页面。1输入问题 2看 Sparkpage 3提取结论", "https://www.genspark.ai", sub_skill_id="research-web-search", sub_skill_label="Web Search & Source QA", importance=84),
        _skill("scite-citation-check", "用 Scite 检查论文引用语境", "ai-research", "Scite", "论文", ["引用", "证据", "论文"], "目的：看论文被支持还是反驳。1查论文 2看引用语境 3写综述", "https://scite.ai", sub_skill_id="research-academic-literature", sub_skill_label="Academic & Literature Review", importance=84),
        _skill("zapier-agents-business", "用 Zapier Agents 做业务自动化代理", "ai-agent", "Zapier Agents", "自动化", ["Agent", "无代码", "自动化"], "目的：让代理跨应用执行。1设目标 2连接应用 3加人工审批", "https://zapier.com/agents", sub_skill_id="agent-workflow-automation", sub_skill_label="Workflow Automation", core=True, importance=86),
        _skill("gumloop-ai-workflow", "用 Gumloop 搭 AI 自动化流程", "ai-agent", "Gumloop", "自动化", ["自动化", "爬取", "工作流"], "目的：把网页、表格和 AI 串起来。1选节点 2设模型 3定时运行", "https://www.gumloop.com", sub_skill_id="agent-workflow-automation", sub_skill_label="Workflow Automation", importance=82),
        _skill("pipedream-ai-workflow", "用 Pipedream 做开发者自动化", "ai-agent", "Pipedream", "自动化", ["API", "Serverless", "集成"], "目的：轻量 serverless workflow。1接触发器 2写步骤 3调用模型", "https://pipedream.com", sub_skill_id="agent-api-mcp-integrations", sub_skill_label="API, MCP & Tool Integrations", importance=80),
        _skill("openai-agents-sdk", "用 OpenAI Agents SDK 搭生产 Agent", "ai-agent", "OpenAI Agents SDK", "开发", ["Agent", "SDK", "工具调用"], "目的：生产级工具型 Agent。1定义工具 2设计交接 3加评测", "https://openai.github.io/openai-agents-python/", sub_skill_id="agent-api-mcp-integrations", sub_skill_label="API, MCP & Tool Integrations", core=True, importance=90),
        _skill("salesforce-agentforce", "用 Salesforce Agentforce 搭 CRM Agent", "ai-business", "Salesforce Agentforce", "业务", ["CRM", "Agent", "销售客服"], "目的：在 CRM 中构建可控业务代理。1定义角色 2连数据 3监控执行", "https://www.salesforce.com/agentforce/", sub_skill_id="business-sales-crm", sub_skill_label="Sales, CRM & Outreach", core=True, importance=88),
        _skill("gong-sales-call-ai", "用 Gong 分析销售通话", "ai-business", "Gong", "销售", ["销售", "通话", "教练"], "目的：复盘销售通话。1接会议 2看异议 3生成跟进", "https://www.gong.io", sub_skill_id="business-sales-crm", sub_skill_label="Sales, CRM & Outreach", importance=82),
        _skill("klaviyo-ai-email", "用 Klaviyo AI 做电邮营销", "ai-business", "Klaviyo AI", "营销", ["电商", "邮件", "营销"], "目的：电商邮件自动化。1分群 2生成内容 3看转化", "https://www.klaviyo.com", sub_skill_id="business-marketing-growth", sub_skill_label="Marketing, SEO & Growth", importance=82),
        _skill("gorgias-ai-support", "用 Gorgias AI 做电商客服", "ai-business", "Gorgias AI", "客服", ["电商", "客服", "工单"], "目的：电商售前售后。1接店铺 2自动回答 3升级人工", "https://www.gorgias.com", sub_skill_id="business-support-community", sub_skill_label="Support, Community & Moderation", importance=78),
    ]


def hot_ai_library_items() -> list[dict]:
    return [
        _combo("combo-hot-models-research", "ChatGPT Deep Research + Perplexity + Claude + NotebookLM", "ai-research", ["ChatGPT Deep Research", "Perplexity", "Claude", "NotebookLM"], "先用 Deep Research 和 Perplexity 拉全网来源，再用 NotebookLM 固化可信资料，最后交给 Claude 写结构化报告和决策摘要。", ["research", "deep-research", "source-check"], 94, sub_skill_id="research-web-search", sub_skill_label="Web Search & Source QA"),
        _combo("combo-coding-review-loop", "Claude Code + Cursor/Windsurf + CodeRabbit + GitHub Actions", "ai-coding", ["Claude Code", "Cursor", "Windsurf", "CodeRabbit", "GitHub Actions"], "用 Claude Code 做跨文件修改，Cursor/Windsurf 处理人工微调，CodeRabbit 做 PR 审查，GitHub Actions 保底测试。", ["coding", "review", "ci"], 94, sub_skill_id="coding-code-edit-review", sub_skill_label="Code Edit & Review"),
        _combo("combo-vibe-app-production", "Lovable/Bolt + Firebase Studio + Supabase + Vercel + PostHog", "ai-coding", ["Lovable", "Bolt.new", "Firebase Studio", "Supabase", "Vercel", "PostHog"], "从自然语言原型到可观测的小型产品：生成前端、接数据库和认证、部署上线、埋点验证。", ["saas", "prototype", "deployment"], 92, sub_skill_id="coding-app-prototype", sub_skill_label="App & Prototype Build"),
        _combo("combo-china-model-stack", "DeepSeek + Kimi + Qwen + 腾讯元宝 + 豆包", "ai-models", ["DeepSeek", "Kimi", "Qwen", "腾讯元宝", "豆包"], "中文场景的多模型对照栈：DeepSeek 做推理，Kimi 读长文，Qwen/元宝/豆包覆盖中文生态、搜索和多模态创作。", ["china-ai", "models", "comparison"], 92, sub_skill_id="models-chinese-ecosystem", sub_skill_label="Chinese Model Ecosystem"),
        _combo("combo-local-private-rag-2026", "Ollama + LM Studio + Open WebUI + AnythingLLM + Obsidian", "ai-models", ["Ollama", "LM Studio", "Open WebUI", "AnythingLLM", "Obsidian"], "本地私有知识库组合：本地模型负责问答，AnythingLLM 管资料，Obsidian 保留长期项目记忆。", ["local-llm", "rag", "privacy"], 90, sub_skill_id="models-local-open-source", sub_skill_label="Local & Open Models"),
        _combo("combo-video-ad-factory", "Veo + Runway + Kling + Luma + CapCut + ElevenLabs", "ai-media", ["Veo", "Runway", "Kling", "Luma", "CapCut", "ElevenLabs"], "广告短片生产线：Veo/Runway 负责高质量镜头，可灵/Luma 做备选运动，CapCut 剪辑，ElevenLabs 补配音。", ["video", "ads", "short-form"], 94, sub_skill_id="media-video-editing", sub_skill_label="Video Generation & Editing"),
        _combo("combo-podcast-repurpose", "Descript + OpusClip + ChatGPT + Canva + Buffer", "ai-media", ["Descript", "OpusClip", "ChatGPT", "Canva", "Buffer"], "把播客或直播复用成短视频、图文摘要和社媒排程，适合个人品牌和内容团队。", ["podcast", "repurpose", "social"], 88, sub_skill_id="media-social-publishing", sub_skill_label="Social Content Publishing"),
        _combo("combo-product-visual-commerce", "Photoroom + Krea + Midjourney + Canva + Shopify Sidekick", "ai-business", ["Photoroom", "Krea", "Midjourney", "Canva", "Shopify Sidekick"], "电商视觉和上架组合：商品抠图、场景生成、品牌排版、上架文案和店铺运营联动。", ["ecommerce", "product-visual", "shopify"], 90, sub_skill_id="business-ecommerce-product", sub_skill_label="E-commerce & Product Ops"),
        _combo("combo-office-memory-meeting", "Microsoft 365 Copilot + Granola + Read.ai + Notion AI", "ai-office", ["Microsoft 365 Copilot", "Granola", "Read.ai", "Notion AI"], "企业会议到执行闭环：会议转写、行动项、Office 文档和团队知识库同步。", ["meeting", "office", "knowledge"], 90, sub_skill_id="office-meetings-knowledge", sub_skill_label="Meetings, Notes & Knowledge"),
        _combo("combo-agent-ops-stack", "n8n + Zapier Agents + Gumloop + Pipedream + Claude/OpenAI", "ai-agent", ["n8n", "Zapier Agents", "Gumloop", "Pipedream", "Claude API", "OpenAI Agents SDK"], "中小团队自动化栈：无代码流程处理日常任务，Pipedream 承接开发者接口，Claude/OpenAI 负责判断和生成。", ["automation", "agent", "ops"], 92, sub_skill_id="agent-workflow-automation", sub_skill_label="Workflow Automation"),
        _combo("combo-sales-agentforce-clay", "Salesforce Agentforce + Clay + Apollo + Gong + Claude", "ai-business", ["Salesforce Agentforce", "Clay", "Apollo", "Gong", "Claude"], "销售增长组合：线索补全、CRM Agent、通话复盘和个性化跟进文案形成闭环。", ["sales", "crm", "agentforce"], 92, sub_skill_id="business-sales-crm", sub_skill_label="Sales, CRM & Outreach"),
        _combo("combo-support-rag-2026", "Zendesk/Intercom + Dify + Gorgias + Claude + Linear", "ai-business", ["Zendesk", "Intercom", "Dify", "Gorgias AI", "Claude", "Linear"], "客服自助和产品反馈组合：RAG Bot 回答常见问题，复杂问题升级，产品缺陷自动进入 Linear。", ["support", "rag", "customer"], 90, sub_skill_id="business-support-community", sub_skill_label="Support, Community & Moderation"),
        _workflow("workflow-ai-toolkit-evaluation", "七天完成团队 AI 工具选型", "ai-business", ["ChatGPT", "Claude", "Gemini", "Perplexity", "Microsoft 365 Copilot", "Notion AI", "Cursor", "Runway"], ["工具评分表", "试点名单", "采购建议", "风险清单"], ["列出团队高频任务和数据敏感度", "用 Perplexity/ChatGPT 查工具能力和价格入口", "让 Claude 生成评分维度", "安排 3 个真实任务试点", "记录输出质量、速度、协作和安全问题", "形成采购和禁用建议"], ["tool-selection", "ops", "governance"], 94, sub_skill_id="business-ops-finance-legal", sub_skill_label="Ops, Finance, Legal & HR"),
        _workflow("workflow-ai-market-intel-48h", "48 小时生成市场和竞品情报包", "ai-research", ["Perplexity", "Genspark", "Similarweb", "Semrush", "Claude", "NotebookLM", "Gamma"], ["竞品矩阵", "趋势摘要", "机会假设", "汇报 deck"], ["Perplexity/Genspark 收集公开资料", "Similarweb/Semrush 查流量和关键词", "NotebookLM 固化来源", "Claude 归纳竞品定位和风险", "Gamma 输出汇报 deck"], ["market-intel", "competitive", "deck"], 92, sub_skill_id="research-market-competitive", sub_skill_label="Market & Competitive Intel"),
        _workflow("workflow-ai-course-production", "一周做一套 AI 微课", "ai-office", ["ChatGPT", "Claude", "NotebookLM", "Napkin", "Canva", "Descript", "ElevenLabs"], ["课程大纲", "讲义", "图解", "配音视频", "测验题"], ["NotebookLM 整理资料来源", "ChatGPT/Claude 生成课程结构和脚本", "Napkin 生成概念图", "Canva 制作讲义和封面", "ElevenLabs 生成配音", "Descript 剪成微课", "Claude 生成测验题"], ["course", "education", "content"], 90, sub_skill_id="office-doc-writing", sub_skill_label="Docs, Writing & Translation"),
        _workflow("workflow-ai-launch-campaign", "新品发布全链路 AI 营销活动", "ai-business", ["Claude", "ChatGPT", "Midjourney", "Krea", "Canva", "Klaviyo AI", "Shopify Sidekick", "Buffer"], ["发布文案", "商品视觉", "邮件流程", "社媒排程", "复盘报告"], ["Claude 产出定位和卖点", "ChatGPT 生成多渠道文案", "Midjourney/Krea 做主视觉", "Canva 套版", "Klaviyo 生成邮件流", "Shopify Sidekick 辅助上架", "Buffer 排程发布"], ["launch", "marketing", "ecommerce"], 92, sub_skill_id="business-marketing-growth", sub_skill_label="Marketing, SEO & Growth"),
        _workflow("workflow-ai-research-paper-fast", "两周做论文综述和研究提案", "ai-research", ["Elicit", "Consensus", "Scite", "Zotero", "NotebookLM", "Claude", "Overleaf"], ["文献矩阵", "研究缺口", "提案初稿", "参考文献"], ["Elicit/Consensus 找核心论文", "Scite 检查引用支持关系", "Zotero 管理文献", "NotebookLM 对资料问答", "Claude 生成研究缺口和提案", "Overleaf 整理格式"], ["paper", "literature", "proposal"], 94, sub_skill_id="research-academic-literature", sub_skill_label="Academic & Literature Review"),
        _workflow("workflow-ai-solo-founder-stack", "独立开发者从想法到付费用户", "ai-coding", ["Perplexity", "Claude", "Lovable", "Cursor", "Supabase", "Stripe", "Vercel", "PostHog", "Crisp"], ["MVP", "支付闭环", "用户反馈", "增长实验"], ["Perplexity 验证需求", "Claude 写 PRD 和路线图", "Lovable 生成原型", "Cursor 工程化", "Supabase/Stripe 接数据和支付", "Vercel 上线", "PostHog/Crisp 收集反馈"], ["solo-founder", "mvp", "saas"], 96, sub_skill_id="coding-app-prototype", sub_skill_label="App & Prototype Build"),
    ]
